spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8761
#  no need to register this service as client because it's a server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
